import type { Plan, DayType } from "@/lib/plan/types";

interface Props {
  plan: Plan;
}

const TYPE_META: Record<DayType, { label: string; chip: string }> = {
  cook: { label: "Cook", chip: "bg-emerald-500/15 text-emerald-700 dark:text-emerald-300" },
  order: { label: "Order", chip: "bg-[var(--accent-soft)] text-[var(--brand-deep)] dark:text-[var(--brand-warm)]" },
  dineout: { label: "Dineout", chip: "bg-purple-500/15 text-purple-700 dark:text-purple-300" },
};

export function PlanView({ plan }: Props) {
  const utilisation = Math.min(100, Math.round((plan.total_cost / plan.input.budget) * 100));
  const remaining = plan.input.budget - plan.total_cost;

  return (
    <section className="space-y-6">
      {/* Summary */}
      <div className="rounded-2xl bg-[var(--bg-elevated)] border border-[var(--border)] p-6 shadow-[var(--shadow-card)]">
        <div className="flex items-baseline justify-between flex-wrap gap-3">
          <div>
            <div className="text-xs uppercase tracking-wide text-[var(--fg-muted)]">
              {plan.input.days}-day plan · {plan.input.profile}
            </div>
            <div className="font-display text-4xl font-bold mt-1">
              ₹{plan.total_cost}
              <span className="text-[var(--fg-muted)] text-base ml-2 font-normal">of ₹{plan.input.budget}</span>
            </div>
          </div>
          <div className="text-right">
            <div className="text-xs uppercase tracking-wide text-[var(--fg-muted)]">Saved</div>
            <div className="font-display text-3xl font-bold text-[var(--rating-green)]">
              ₹{Math.max(0, remaining)}
            </div>
          </div>
        </div>
        <div className="mt-4 h-2 bg-[var(--bg-subtle)] rounded-full overflow-hidden">
          <div
            className="h-full bg-gradient-to-r from-[var(--brand-deep)] via-[var(--accent)] to-[var(--brand-warm)] transition-all rounded-full"
            style={{ width: `${utilisation}%` }}
          />
        </div>
        <div className="mt-3 text-xs text-[var(--fg-muted)]">
          {plan.generated_by === "agent"
            ? "Generated by Llama 3.3 70B on Groq across 3 MCP servers"
            : "Generated deterministically · Llama agent ships in Phase 2"}
        </div>
      </div>

      {/* Day cards */}
      <div className="space-y-2">
        {plan.days.map((d) => {
          const t = TYPE_META[d.type];
          return (
            <div
              key={d.day}
              className="rounded-xl bg-[var(--bg-elevated)] border border-[var(--border)] p-4 flex items-center gap-4 hover:border-[var(--border-strong)] transition-colors"
            >
              <div className="w-12 text-center">
                <div className="text-xs uppercase text-[var(--fg-muted)]">Day {d.day}</div>
                <div className="font-mono text-sm font-medium">{d.weekday}</div>
              </div>

              <div className="flex-1 min-w-0">
                <div className="flex items-center gap-2 mb-1">
                  <span className={`px-2 py-0.5 rounded-md text-xs font-medium ${t.chip}`}>
                    {t.label}
                  </span>
                  {d.meta?.coupon && (
                    <span className="px-2 py-0.5 rounded-md text-xs font-bold bg-[var(--accent-soft)] text-[var(--brand-deep)] dark:text-[var(--brand-warm)]">
                      {d.meta.coupon}
                    </span>
                  )}
                  {d.meta?.travel && (
                    <span className="px-2 py-0.5 rounded-md text-xs font-medium bg-[var(--bg-subtle)] text-[var(--fg-muted)]">
                      {d.meta.travel}
                    </span>
                  )}
                </div>
                <div className="text-sm font-medium truncate">{d.description}</div>
                {d.meta?.slot && (
                  <div className="text-xs text-[var(--fg-muted)] mt-0.5">{d.meta.slot}</div>
                )}
              </div>

              <div className="text-right">
                <div className="font-mono font-semibold">{d.cost === 0 ? "—" : `₹${d.cost}`}</div>
                <div className="text-xs text-[var(--fg-muted)]">{d.source}</div>
              </div>
            </div>
          );
        })}
      </div>

      {/* Recipes from your cart */}
      {plan.recipes.length > 0 && (
        <div className="rounded-2xl bg-[var(--bg-elevated)] border border-[var(--border)] overflow-hidden">
          <div className="px-6 py-4 border-b border-[var(--border)] flex items-baseline justify-between">
            <div>
              <div className="text-xs uppercase tracking-wide text-[var(--fg-muted)]">
                What to cook
              </div>
              <div className="text-base font-semibold mt-0.5">From your Instamart cart</div>
            </div>
            <div className="text-xs text-[var(--fg-muted)]">
              tuned for {plan.input.profile}
            </div>
          </div>
          <ul className="divide-y divide-[var(--border)]">
            {plan.recipes.map(({ recipe, meal_time }) => (
              <li key={recipe.id} className="px-6 py-3 flex items-center gap-4">
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-2 mb-0.5">
                    <span className="text-sm font-semibold">{recipe.name}</span>
                    <span className="text-xs px-1.5 py-0.5 rounded bg-[var(--bg-subtle)] text-[var(--fg-muted)] capitalize">
                      {meal_time}
                    </span>
                  </div>
                  <div className="text-xs text-[var(--fg-muted)] line-clamp-1">{recipe.blurb}</div>
                </div>
                <div className="text-xs text-[var(--fg-muted)] whitespace-nowrap">
                  {recipe.prep_minutes} min
                </div>
              </li>
            ))}
          </ul>
        </div>
      )}

      {/* Cart breakdown */}
      <details className="rounded-2xl bg-[var(--bg-elevated)] border border-[var(--border)] overflow-hidden group">
        <summary className="px-6 py-4 cursor-pointer select-none flex items-center justify-between">
          <div>
            <div className="text-xs uppercase tracking-wide text-[var(--fg-muted)]">
              Instamart cart
            </div>
            <div className="text-sm font-semibold mt-0.5">
              {plan.instamart_cart.lines.length} items · ₹{plan.instamart_cart.total} ·{" "}
              <span className="text-[var(--fg-muted)] font-normal">
                ~{plan.instamart_cart.serves_meals} meals
              </span>
            </div>
          </div>
          <span className="text-[var(--fg-muted)] group-open:rotate-180 transition-transform">▾</span>
        </summary>
        <ul className="px-6 pb-4 divide-y divide-[var(--border)] text-sm">
          {plan.instamart_cart.lines.map((line) => (
            <li key={line.sku} className="py-2 flex justify-between font-mono">
              <span>{line.name}</span>
              <span className="text-[var(--fg-muted)]">₹{line.price}</span>
            </li>
          ))}
        </ul>
      </details>

      {/* Dineout booking detail */}
      {plan.dineout_booking && (
        <div className="rounded-2xl bg-[var(--bg-elevated)] border border-[var(--border)] p-6">
          <div className="flex items-baseline justify-between mb-3">
            <div>
              <div className="text-xs uppercase tracking-wide text-[var(--fg-muted)]">Dineout</div>
              <div className="text-base font-semibold mt-0.5">{plan.dineout_booking.restaurant}</div>
              <div className="text-xs text-[var(--fg-muted)]">{plan.dineout_booking.area}</div>
            </div>
            <span className="px-2 py-1 rounded-md bg-[var(--discount-red)]/10 text-[var(--discount-red)] text-xs font-bold">
              {plan.dineout_booking.discount_percent}% OFF
            </span>
          </div>
          <div className="grid grid-cols-3 gap-3 text-sm font-mono">
            <Stat label="When" value={plan.dineout_booking.slot} />
            <Stat label="Per person" value={`₹${plan.dineout_booking.per_person_cost}`} />
            <Stat
              label="Travel"
              value={
                plan.dineout_booking.travel_minutes != null
                  ? `${plan.dineout_booking.travel_minutes} min`
                  : "—"
              }
            />
          </div>
        </div>
      )}
    </section>
  );
}

function Stat({ label, value }: { label: string; value: string }) {
  return (
    <div>
      <div className="text-xs text-[var(--fg-muted)] uppercase tracking-wide">{label}</div>
      <div className="text-sm mt-0.5">{value}</div>
    </div>
  );
}
